<a href="https://colab.research.google.com/github/mgultekin/AiForMedicalDiagnosis/blob/main/Course1W3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Extract a sub-section

In [10]:
#In this lab, i am going to extract sub-section from 1D array to learn make the same thing for 3D MRI volume

In [11]:
import numpy as np
import keras
import pandas as pd

In [12]:
#1D image to extract from
image = np.array([20,21,22,23,24,25])
image

array([20, 21, 22, 23, 24, 25])

In [13]:
#lets see the dimensions of the image

image_length = image.shape[0]
image_length

6

**Sub-sections**

In [14]:
#patch size in three dimension that is the size of extracted sub-section
patch_length = 3

In [23]:
#define start index
start_i = 0

In [24]:
end_i = start_i + patch_length
print('end index is: ', end_i)

#extract a sub-section from the image

sub_section = image[start_i : end_i]
print('Output patch length is: ', len(sub_section))
print('Output patch array: ', sub_section)

start_i += 1

end index is:  3
Output patch length is:  3
Output patch array:  [20 21 22]


In [26]:
# Compute and print the largest valid value for start index
print(image_length - patch_length)

3


In [31]:
# Compute and print the range of valid start indices
valid_start_ind = [i for i in range(image_length - patch_length + 1)]
valid_start_ind

[0, 1, 2, 3]

**Random selection of start indices**

In [34]:
for i in range(10):
    start_ind = np.random.randint(image_length - patch_length +1)
    print('Randomly selected start index', start_ind)

Randomly selected start index 3
Randomly selected start index 3
Randomly selected start index 2
Randomly selected start index 0
Randomly selected start index 1
Randomly selected start index 3
Randomly selected start index 2
Randomly selected start index 0
Randomly selected start index 0
Randomly selected start index 3


**Background Ratio**

In [35]:
#lets say we have 4 different label represents diseases, and now i am going to simulate input data by defining random patch of length 16

patch_labels = np.random.randint(0,4,16)
print(patch_labels)

[1 3 2 3 3 2 2 0 1 1 2 1 1 2 0 0]


In [36]:
#now im going to get backround ratio by counting 0s (0 means 'background' )
bgrd_ratio = np.count_nonzero(patch_labels == 0) / len(patch_labels)

print('Background ratio is: ', bgrd_ratio)

Background ratio is:  0.1875


In [38]:
#BUT first, we need to convert our patch labels to one hot format so it can be used to train network
patch_labels_one_hot = keras.utils.to_categorical(patch_labels, num_classes= 4)
print(patch_labels_one_hot)

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [39]:
#lets convert our output to dataframe with labels to see more clearly

pd.DataFrame(patch_labels_one_hot, columns=['background', 'edema', 'non-enhancing tumor', 'enhancing tumor'])

background  edema  non-enhancing tumor  enhancing tumor
0          0.0    1.0                  0.0              0.0
1          0.0    0.0                  0.0              1.0
2          0.0    0.0                  1.0              0.0
3          0.0    0.0                  0.0              1.0
4          0.0    0.0                  0.0              1.0
5          0.0    0.0                  1.0              0.0
6          0.0    0.0                  1.0              0.0
7          1.0    0.0                  0.0              0.0
8          0.0    1.0                  0.0              0.0
9          0.0    1.0                  0.0              0.0
10         0.0    0.0                  1.0              0.0
11         0.0    1.0                  0.0              0.0
12         0.0    1.0                  0.0              0.0
13         0.0    0.0                  1.0              0.0
14         1.0    0.0                  0.0              0.0
15         1.0    0.0                  0.0              0.0

In [40]:
print('background column: ', patch_labels_one_hot[:,0])

background column:  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1.]


In [41]:
#now we can compute background ratio by counting number of 1s
back_ratio = np.sum(patch_labels_one_hot[:,0]) / len(patch_labels)
print('Background ratio is: ', back_ratio)

Background ratio is:  0.1875
